{
  "formatVersion": "1.1",
  "component": {
    "group": "com.robin.javassist.plugin",
    "module": "buglyBug",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "buglyBug-1.0.0.jar",
          "url": "buglyBug-1.0.0.jar",
          "size": 16067,
          "sha512": "7a6d43adcec12cba8fda9cd0c3666ba0f3f701faf3642a5c4d1d5813177cb6a364fc308f61249fc2d07fba55ae154acc94e4b49b8f738adcf74ab22f6080ab38",
          "sha256": "ea43b0c542bb1e3fc772b405ae85bedaef0666a5ed9e7f249c65cf9514f7398f",
          "sha1": "7a734b0806a550ae04fab2945debffade0bc3d02",
          "md5": "3050070ab0c863dde614700d14d06cd9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.30.2-GA"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "buglyBug-1.0.0.jar",
          "url": "buglyBug-1.0.0.jar",
          "size": 16067,
          "sha512": "7a6d43adcec12cba8fda9cd0c3666ba0f3f701faf3642a5c4d1d5813177cb6a364fc308f61249fc2d07fba55ae154acc94e4b49b8f738adcf74ab22f6080ab38",
          "sha256": "ea43b0c542bb1e3fc772b405ae85bedaef0666a5ed9e7f249c65cf9514f7398f",
          "sha1": "7a734b0806a550ae04fab2945debffade0bc3d02",
          "md5": "3050070ab0c863dde614700d14d06cd9"
        }
      ]
    }
  ]
}
